import React, { useEffect, useState } from "react";
import Header from "./components/Header";
import Image from "next/legacy/image";
import Team from "../constant/teamNames.json";
import { motion } from "framer-motion";

import {
  FaFacebook,
  FaGithub,
  FaLinkedin,
  FaInstagram,
  FaTwitter,
} from "react-icons/fa";

import Link from "next/link";
import Head from "next/head";
import useLocalStorage from "use-local-storage";

const Contact = () => {
  const [x, setX] = useLocalStorage("Mode", false);
  const toggleTheme = () => {
    setX(!x);
  };

  useEffect(() => {
    async () => {
      let Members = fetch("../constant/teamNames.json")
        .then((res) => res.json())
        .then((data) => console.log(data));
    };
  }, []);

  return (
    <>
      <motion.div
        className={`${
          x ? "dark" : ""
        } flex flex-col justify-end bg-white dark:bg-gray-600 h-screen scrollbar-thin scrollbar-thumb-[#FF5A5F] scrollbar-track-gray-500 overflow-y-scroll`}
      >
        <Head>
          <title>Contact Us</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/fav.png" />
        </Head>
        <Header onDarkToggle={toggleTheme} />

        <div className="absolute w-screen h-screen  flex flex-col items-center bg-white dark:bg-gray-700">
          <motion.div
            initial={{
              y: -100,
              opacity: 0,
            }}
            animate={{
              y: 0,
              opacity: 1,
            }}
            transition={{
              duration: 1.3,
            }}
            className="mt-24 text-center text-[3rem] sm:text-[4rem] md:text-[4.5rem] lg:text-[5rem] font-Josefin text-[#FF5A5F]"
          >
            TEAM MEMBERS
          </motion.div>

          {/* <div className="flex overflow-x-scroll justify-between sm:grid-cols-2 xl:grid-cols-3"> */}
          <div className="flex w-full space-x-5 overflow-x-scroll scrollbar-thin scrollbar-thumb-[#FF5A5F] scrollbar-track-gray-500/40 items-center p-6 snap-x snap-mandatory">
            {Team &&
              Team.map((item, index) => {
                return (
                  <li key={index} className="list-none">
                    <div className="flex snap-center flex-col items-center border bg-[#292929]/10 dark:bg-[#292929]/70 rounded-lg p-10">
                      <div className="items-center">
                        <Image
                          src={item.imgLink}
                          height={100}
                          width={100}
                          alt="Students Image"
                          className="rounded-full"
                        />
                      </div>
                      <div className="p-3 items-center">
                        <p className="text-gray-900 text-center dark:text-gray-200 text-sm font-bold">
                          {item.fullName}
                        </p>
                        <div className="bg-transparent flex">
                          <div className="flex space-x-3">
                            <Link href={item.githubLink}>
                              <FaGithub className="text-gray-400 hover:text-black dark:hover:text-black dark:text-gray-400" />
                            </Link>
                            <Link href={item.linkedIn}>
                              <FaLinkedin className="text-gray-400 hover:text-blue-700 dark:hover:text-blue-700 dark:text-gray-400" />
                            </Link>
                            <Link href={item.insta}>
                              <FaInstagram className="text-gray-400 hover:text-pink-600 dark:hover:text-pink-600 dark:text-gray-400" />
                            </Link>
                            <Link href={item.facebook}>
                              <FaFacebook className="text-gray-400 hover:text-blue-700 dark:hover:text-blue-700 dark:text-gray-400" />
                            </Link>
                            <Link href={item.twitter}>
                              <FaTwitter className="text-gray-400 hover:text-cyan-600 dark:hover:text-cyan-600 dark:text-gray-400" />
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>
                  </li>
                );
              })}
          </div>
        </div>
      </motion.div>
    </>
  );
};

export default Contact;
