import Head from "next/head";
import React, { useState } from "react";
import Feature from "./components/Feature";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Subscribe from "./components/Subscribe";
import { motion } from "framer-motion";
import useLocalStorage from "use-local-storage";
import { useEffect } from "react";
import { data } from "autoprefixer";
import { async } from "@firebase/util";

const Features = (name, photo) => {
  const [x, setX] = useLocalStorage("Mode", false);
  const toggleTheme = () => {
    setX(!x);
  };

  return (
    <>
      <motion.div
        className={`${
          x ? "dark" : ""
        } flex flex-col h-screen  bg-white dark:bg-gray-600 scrollbar-thin scrollbar-thumb-[#FF5A5F] scrollbar-track-gray-500 overflow-y-scroll overscroll-x-none`}
      >
        <Head>
          <title>Features</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/fav.png" />
        </Head>
        <Header onDarkToggle={toggleTheme} />

        <Feature />

        <Subscribe />

        <Footer />
      </motion.div>
    </>
  );
};

export default Features;
