import Head from "next/head";
import React, { useState } from "react";
import Feature from "./components/Feature";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Subscribe from "./components/Subscribe";

const Features = () => {
  const [x, setX] = useState(false);
  const toggleTheme = () => {
    setX(!x);
  };

  return (
    <>
      <div
        className={`${
          x ? "dark" : ""
        } flex flex-col justify-end h-screen bg-white dark:bg-gray-600 scrollbar-thin scrollbar-thumb-[#FF5A5F] scrollbar-track-gray-500 overflow-y-scroll`}
      >
        <Head>
          <title>Features</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/fav.png" />
        </Head>
        <Header onDarkToggle={toggleTheme} />

        <Feature />

        <Subscribe />

        <Footer />
      </div>
    </>
  );
};

export default Features;
