import { ArrowRightCircleIcon } from "@heroicons/react/24/outline";
import Head from "next/head";
import Link from "next/link";
import React, { useState } from "react";
import Header from "./components/Header";

const Letstest = () => {
  const [x, setX] = useState(false);
  const toggleTheme = () => {
    setX(!x);
  };

  return (
    <div className={`${x ? "dark" : ""} w-full h-screen scrollbar-thin scrollbar-thumb-[#FF5A5F] scrollbar-track-gray-500 overflow-y-scroll overscroll-x-none `}>
      <Head>
        <title>Let&apos;s Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png" />
      </Head>
      <Header onDarkToggle={toggleTheme} className="" />

      <div className="flex flex-col items-center mt-6 bg-white dark:bg-gray-700 ">

        <div className=" py-14 text-[4.2rem] sm:text-[4.5rem] md:text-[4.8rem] lg:text-[5.5rem] font-Josefin text-[#FF5A5F]">
          Let&apos;s Test
        </div>
        <div className="p-5 m-6 w-[100%] bg-gray-300 rounded-xl">
          <div className="">
            <ul className="items-center list-decimal list-outside  p-5 m-2 ">
              {/* First Question */}
              <li key={1} className="text-start text-lg text-black font-bold">
                How often have you had little interest or pleasure in doing
                things?
              </li>

              <div className="py-2 text-black">
                <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                  <input
                    id="bordered-radio-1"
                    type="radio"
                    value=""
                    name="radio_one"
                    className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                  />
                  <label
                    htmlFor="bordered-radio-1"
                    className="py-4 ml-2 w-full text-md font-normal text-gray-900 "
                  >
                    Not at all
                  </label>
                </div>
                <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                  <input
                    id="bordered-radio-1"
                    type="radio"
                    value=""
                    name="radio_one"
                    className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                  />
                  <label
                    htmlFor="bordered-radio-1"
                    className="py-4 ml-2 w-full text-md font-normal text-gray-900 "
                  >
                    Several days
                  </label>
                </div>
                <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                  <input
                    id="bordered-radio-1"
                    type="radio"
                    value=""
                    name="radio_one"
                    className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                  />
                  <label
                    htmlFor="bordered-radio-1"
                    className="py-4 ml-2 w-full text-md font-normal text-gray-900 "
                  >
                    More than half the days
                  </label>
                </div>
                <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                  <input
                    id="bordered-radio-1"
                    type="radio"
                    value=""
                    name="radio_one"
                    className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                  />
                  <label
                    htmlFor="bordered-radio-1"
                    className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                  >
                    Nearly Everyday
                  </label>
                </div>
              </div>
              {/* Second Question */}

              <li key={2} className="text-start text-lg text-black font-bold">
                How often have you been bothered by feeling tired or having
                little energy?
              </li>

              <div className="py-2 ">
                <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                  <input
                    id="bordered-radio-1"
                    type="radio"
                    value=""
                    name="radio_two"
                    className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                  />
                  <label
                    htmlFor="bordered-radio-1"
                    className="py-4 ml-2 w-full text-md font-normal text-gray-900 "
                  >
                    Not at all
                  </label>
                </div>
                <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                  <input
                    id="bordered-radio-1"
                    type="radio"
                    value=""
                    name="radio_two"
                    className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                  />
                  <label
                    htmlFor="bordered-radio-1"
                    className="py-4 ml-2 w-full text-md font-normal text-gray-900 "
                  >
                    Several days
                  </label>
                </div>
                <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                  <input
                    id="bordered-radio-1"
                    type="radio"
                    value=""
                    name="radio_two"
                    className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                  />
                  <label
                    htmlFor="bordered-radio-1"
                    className="py-4 ml-2 w-full text-md font-normal text-gray-900 "
                  >
                    More than half the days
                  </label>
                </div>
                <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                  <input
                    id="bordered-radio-1"
                    type="radio"
                    value=""
                    name="radio_two"
                    className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                  />
                  <label
                    htmlFor="bordered-radio-1"
                    className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                  >
                    Nearly Everyday
                  </label>
                </div>
                {/* Third Question */}

                <li key={3} className="text-start text-lg text-black font-bold">
                  How often have you been bothered by trouble falling or staying
                  asleep&sbquo; or sleeping too much?
                </li>

                <div className="py-2 ">
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_three"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="Namepy-4 py-4 ml-2 w-full text-md font-normal text-gray-900 "
                    >
                      Not at all
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_three"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900 "
                    >
                      Several days
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_three"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      More than half the days
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_three"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Nearly Everyday
                    </label>
                  </div>
                </div>

                {/* Fourth Question */}

                <li key={4} className="text-start text-lg text-black font-bold">
                  How often do you feel that all your hobbies and interests are
                  boring and worthless and nothing can stimulate you?
                </li>

                <div className="py-2 ">
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_four"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Not at all
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_four"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Several days
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_four"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      More than half the days
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_four"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Nearly Everyday
                    </label>
                  </div>
                </div>
                {/* Fiveth Question */}

                <li key={5} className="text-start text-lg text-black font-bold">
                  How often have you been bothered by feeling bad about
                  yourself, or that you are a failure&sbquo; or have let yourself or
                  your family down?
                </li>

                <div className="py-2 ">
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_five"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900 "
                    >
                      Not at all
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_five"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Several days
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_five"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      More than half the days
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_five"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Nearly Everyday
                    </label>
                  </div>
                </div>
                {/* Sixth Question */}

                <li key={6} className="text-start text-lg text-black font-bold">
                  Are you afraid of forming a new relationship and feel scared
                  of attachment?
                </li>

                <div className="py-2 ">
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_six"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Not at all
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_six"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Several days
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_six"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      More than half the days
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_six"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Nearly Everyday
                    </label>
                  </div>
                </div>
                {/* Seventh Question */}

                <li key={7} className="text-start text-lg text-black font-bold">
                  How often you have an anxiety attack (suddenly feeling fear or
                  panic)?
                </li>
                <div className="text-start text-sm text-gray-600 font-medium">
                  <p className="pt-3">
                    An anxiety or panic attack occurs when your body experiences
                    a rush of intense psychological (mental) and physical
                    symptoms.
                  </p>
                  <p className="pt-3">
                    You may feel an overwhelming sense of fear&sbquo; apprehension and
                    anxiety. As well as these feelings&sbquo; you may also experience
                    physical symptoms such as:
                  </p>
                  <ul className="px-10 list-disc list-outside ">
                    <li key={0} className="text-gray-500">
                      Nausea
                    </li>
                    <li key={1} className="text-gray-500">
                      Sweating
                    </li>
                    <li key={2} className="text-gray-500">
                      Trembling
                    </li>
                  </ul>
                </div>
                {/* Eigth Question */}

                <div className="py-2 ">
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="bordered-radio"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Not at all
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="bordered-radio"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Several days
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="bordered-radio"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      More than half the days
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="bordered-radio"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Nearly Everyday
                    </label>
                  </div>
                </div>
                <li key={8} className="text-start text-lg text-black font-bold">
                  How often have you been bothered by feeling nervous&sbquo; anxious
                  or on edge?
                </li>
                {/* Nineth Question */}
                <div className="py-2 ">
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_seven"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Not at all
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_seven"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Several days
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_seven"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      More than half the days
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_seven"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Nearly Everyday
                    </label>
                  </div>
                </div>
                <li key={9} className="text-start text-lg text-black font-bold">
                  How often have you been bothered by feeling afraid as if
                  something awful might happen?
                </li>
                {/* Tenth Question */}

                <div className="py-2 ">
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_eight"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Not at all
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_eight"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Several days
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_eight"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      More than half the days
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_eight"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Nearly Everyday
                    </label>
                  </div>
                </div>
                <li
                  key={10}
                  className="text-start text-lg text-black font-bold"
                >
                  How often do you feel guilty or tearful for no reason?
                </li>

                <div className="py-2 ">
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_ten"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Not at all
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_ten"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Several days
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_ten"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="bordered-radio-1"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      More than half the days
                    </label>
                  </div>
                  <div className="flex items-center pl-4 m-2 rounded border w-[20rem] border-gray-500 dark:border-gray-700">
                    <input
                      id="bordered-radio-1"
                      type="radio"
                      value=""
                      name="radio_ten"
                      className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <label
                      htmlFor="radio_ten"
                      className="py-4 ml-2 w-full text-md font-normal text-gray-900"
                    >
                      Nearly Everyday
                    </label>
                  </div>
                </div>
              </div>
            </ul>
          </div>
          <div className="flex items-center justify-center">
            <Link href="./result">
              <button className="bg-[#FF5A5F] flex justify-between py-3 px-6 text-white rounded-lg shadow-sm hover:shadow-xl active:scale-90 transition duration-150 ">
                Submit
                <ArrowRightCircleIcon className="pl-3 h-6 items-center text-white" />
              </button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Letstest;
