import Head from "next/head";
import React, { useState } from "react";
import ADM from "../image-assets/ADM.png";
import LoginSet from "../image-assets/login_setter.png";
import Google from "../image-assets/google.png";
import Image from "next/image";
import { onAuthStateChanged, signInWithPopup } from "firebase/auth";
import { auth, provider } from "../firebase";
import { useRouter } from "next/router";
import { useEffect } from "react";

const Login = () => {
  const router = useRouter();

  useEffect(() => {
    onAuthStateChanged(auth, (user) => {
      if (user) {
        router.push("/");
      }
    });
  });

  return (
    <div className="">
      <Head>
        <title>Register your Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png" />
      </Head>
      <section className="flex flex-col p-4 bg-red-100 h-screen overflow-y-auto dark:bg-gray-500">
        {/* <div className="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0 mt-16">
          <div className="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
            <div className="p-6 space-y-4 md:space-y-6  sm:p-8">
              <h1 className="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                Register Your New Account
              </h1>
              <form className="space-y-4 md:space-y-6" action="#">
                <div>
                  <label
                    for="email"
                    className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                  >
                    Enter Your Email
                  </label>
                  <input
                    type="email"
                    name="email"
                    id="email"
                    className="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                    placeholder=""
                    required=""
                  />
                  <div>
                    <label
                      for="password"
                      className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                    >
                      Password
                    </label>
                    <input
                      type="password"
                      name="password"
                      id="password"
                      placeholder="••••••••"
                      className="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                      required=""
                    />
                  </div>
                  <div>
                    <label
                      for="confirm-password"
                      className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                    >
                      Confirm password
                    </label>
                    <input
                      type="password"
                      name="confirm-password"
                      id="confirm-password"
                      placeholder="••••••••"
                      className="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                      required=""
                    />
                  </div>
                  <div className="flex items-start"></div>
                  <button
                    type="submit"
                    className="w-full text-white bg-primary-600 border-none bg-[#FF5A5F]  font-bold rounded-lg text-md px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800  border-2 border-black mt-5 hadow-sm hover:shadow-xl active:scale-90 transition duration-150  "
                  >
                    Submit
                  </button>
                  <div className="text-blue-800 pt-2 text-center dark:text-cyan-200 text-sm cursor-pointer active:scale-90 transition duration-150">
                    Already having account?
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div> */}

        <Image
          src={ADM}
          objectFit="contain"
          height={50}
          width={100}
          className="m-3 w-auto self-start"
          alt="Logo"
          viewBox="0 0 20 20"
        />

        <h2 className="text-4xl pt-4 text-gray-500">
          Log in to access your account
        </h2>
        <div className="flex items-center justify-center">
          <Image src={LoginSet} alt="Login Set" objectFit="contain" width={400} />
        </div>

        {/* <button
          className="bg-black text-white py-4 px-8 mt-8 text-center self-center w-full"
          onClick={() => signInWithPopup(auth, provider)}
        >
          Sign in with Google
        </button> */}
        <div
          className="bg-black text-white py-4 px-8 mt-8 flex space-x-3 text-center justify-center items-center cursor-pointer self-center w-[90%] md:w-[80%] lg:w-[70%] xl:w-[60%] 2xl:w-[50%] "
          onClick={() => signInWithPopup(auth, provider)}
        >
          <Image
            objectFit="contain"
            height={25}
            width={25}
            src={Google}
            alt="Google"
          />
          <div className="text-white font-bold ">Continue with Google</div>
        </div>
      </section>
    </div>
  );
};

export default Login;
